version: '3.9'
services:

  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    command: [ "sh", "-c", "/cloud-native-go/bin/migrate up && /cloud-native-go/bin/app" ]
    restart: always

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=myapp_db
      - POSTGRES_USER=myapp_user
      - POSTGRES_PASSWORD=myapp_pass
    ports:
      - "5432:5432"
    restart: always